version: "3"

services:
  database:
    container_name: database_${IMAGE_TAG}
    build:
      context: ./database
      args:
        POSTGRES_USER:     ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        APP_USER:          ${APP_USER}
        APP_PASSWORD:      ${APP_PASSWORD}
        APP_DATABASE:      ${APP_DATABASE}
        WEB_USER:          ${WEB_USER}
        WEB_PASSWORD:      ${WEB_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_CONTAINER_PORT}
    depends_on:
      - adminer_${IMAGE_TAG}

  adminer:
    container_name: adminer_${IMAGE_TAG}
    build:
      context: ./adminer
      args:
        ADMINER_DEFAULT_DATABASE_DRIVER: pgsql
        ADMINER_DEFAULT_SERVER:          database
        ADMINER_DEFAULT_USER:            ${APP_USER}
        ADMINER_DEFAULT_DATABASE_NAME:   ${APP_DATABASE}
        ADMINER_DESIGN: rmsoft
    ports:
      - ${ADMINER_PORT}:${ADMINER_CONTAINER_PORT}
